# ---------------------------------------------------------------------------
#
# Test script for the HTML interface, loaded by TestHTML.tst
#
# Copyright (c) 2001-2011 John Graham-Cumming
#
#   This file is part of POPFile
#
#   POPFile is free software; you can redistribute it and/or modify it
#   under the terms of version 2 of the GNU General Public License as
#   published by the Free Software Foundation.
#
#   POPFile is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with POPFile; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# ---------------------------------------------------------------------------

# To simplify testing the POPFile HTML UI this file contains a script
# that is read by TestHTML.tst and executed.  The script consists of instructions
# for specific URLs that are to be hit and instructions for how to match the
# result that comes back
#
# The commands are as follows
#
# GET <url>         Get the URL (note the host and port will be added for you)
# MATCH <data>      Match the return from last URL fetch against the data
# NOTMATCH <data>   Must not match the return from last URL fetch against the data
# MATCH/ENDMATCH    Encloses a block of test to find in the return from the last URL fetch
# CODE/ENDCODE      Arbitrary code that should be executed
# INPUTIS a b       Assert that form item a has value b
# SETINPUT a b      Sets the form item a to value b
# SETINPUTN a b c   Sets the bth input named a to c
# SUBMIT a          Finds the form with input a and submits it
# SETSUBMIT a b     Just like doing SETINPUT a b followed by SUBMIT a
# CONFIGIS a b      Verify that config item a has value b
# SETCONFIG a b     Set config item a to b
# MAGNETIS a b c    Checks that magnet c exists in bucket a with type b
# PARAMETERIS a b c Check that parameter b in bucket a has value c
# CLICK a           Click the button called a
# SENDMSG a b       Send a message through the POPFile MQ (message a with parameter b)
# STOP              Terminate the script, used for debugging
# HIDDEN a          If a is 1 then allow matching on hidden form elements
#                   (by default this is 0)
#
# Expect that the following are available to you within the MATCH/ENDMATCH block
#
# $port             The port on which the HTML interface is running
# $url              URL object for the last URL specified
# $content          String containing the return from the last URL fetch
# $sk               The current HTML UI session key
# $version          Same as $h->version()

# Test the simplest functionality of the HTML interface

# Look for elements that should appear at the TOP and BOTTOM
# of every page

GET /

# Common TOP parts

MATCH <title>POPFile Control Center</title>
MATCH <html lang="en">
MATCH <link rel="stylesheet" type="text/css" href="skins/simplyblue/style.css" title="POPFile">
MATCH <link rel="icon" href="favicon.ico">

MATCH <a class="shutdownLink" href="/shutdown">Shutdown POPFile</a>

# Common MIDDLE parts (i.e. the tabs)

MATCH <a class="menuLink" href="/history?session=$sk">
MATCH History</a>
MATCH <a class="menuLink" href="/buckets?session=$sk">
MATCH Buckets</a>
MATCH <a class="menuLink" href="/magnets?session=$sk&amp;start_magnet=0">
MATCH Magnets</a>
MATCH <a class="menuLink" href="/configuration?session=$sk">
MATCH Configuration</a>
MATCH <a class="menuLink" href="/security?session=$sk">
MATCH Security</a>
MATCH <a class="menuLink" href="/advanced?session=$sk">
MATCH Advanced</a>

# Common BOTTOM parts

MATCH <a class="bottomLink" href="http://getpopfile.org/">POPFile Home Page</a>
MATCH <a class="bottomLink" href="http://getpopfile.org/docs/FAQ">FAQ</a>
MATCH <a class="bottomLink" href="http://getpopfile.org/docs/index.php">Documentation</a>
MATCH $version

# Verify that each of the pages highlights the correct item on
# the tab bar and hence the simplest level of page serving is working
# correctly

GET /history
MATCH
<td class="menuSelected" align="center">
                <a class="menuLink" href="/history?session=$sk">
ENDMATCH

GET /buckets
MATCH
<td class="menuSelected" align="center">
                <a class="menuLink" href="/buckets?session=$sk">
ENDMATCH

GET /magnets
MATCH
<td class="menuSelected" align="center">
                <a class="menuLink" href="/magnets?session=$sk&amp;start_magnet=0">
ENDMATCH

GET /configuration
MATCH
<td class="menuSelected" align="center">
                <a class="menuLink" href="/configuration?session=$sk">
ENDMATCH

GET /security
MATCH
<td class="menuSelected" align="center">
                <a class="menuLink" href="/security?session=$sk">
ENDMATCH

GET /advanced
MATCH
<td class="menuSelected" align="center">
                <a class="menuLink" href="/advanced?session=$sk">
ENDMATCH

# History Page

GET /history

# Check for existence of messages, check that there
# are links from the bucket names, check that the basic
# sort options are present

MATCH &quot;Dr. Robert Ezenshtein&quot; &lt;phrekiesomeone\@
MATCH &quot;Sheck-Buy&quot; &lt;ADV\@Sheck-Buy.com&gt;
MATCH &lt;from header missing&gt;
MATCH &quot;Becky&quot;  &lt;81355329526\@mail2.great-babes-online.com&gt;
MATCH &quot;Willie Eason&quot; &lt;5x8njuc1ydwu\@mail2Honey.com&gt;
MATCH test\@test.com
MATCH &quot;MARGIT&quot; &lt;cxcse231\@yahoo.com&gt;
MATCH Sascha Schwabbauer &lt;cybersystem\@gentoo.o...
MATCH &lt;bugs\@drnn.net&gt;
MATCH &lt;elia\@tpkm.ru&gt;
MATCH hottest_site_on_net22840\@yahoo.com
MATCH wendyoufp\@msn.com
MATCH Douglas Arnold &lt;0noy8\@worldnet.att.net&gt;
MATCH RN &lt;rrr\@nnnnnnnnn.com&gt;
MATCH Brianna121 &lt;Brianna121\@aol.com&gt;
MATCH &quot;Acaynya&quot;&lt;hornydarla3553qqoe1\@free.fr&gt;

MATCH asdfsomebody\@mbnet.fi
MATCH &lt;to header missing&gt;
MATCH xxx\@xxx.net
MATCH &quot;Willie Eason&quot; &lt;5x8njuc1ydwu\@mail2Honey....
MATCH someone\@somewhere.com
MATCH dsmith\@ctaz.com, dsmith\@dol.net, dsmith\@dirtur.com, dsmith\@dialpoint.net, dsmith\@crosscountybank.com,	&lt;dsmith\@cybersurf.net&gt;, &lt;dsmith\@dotnet.com&gt;, &lt;dsmith\@db.com&gt;, &lt;dsmith\@cs.com&gt;	, &lt;dsmith\@crossville.com&gt;,	&lt;dsmith\@dreamscape.com&gt;, &lt;dsmith\@cvnc.net&gt;, &lt;dsmith\@dmrtc.net&gt;, &lt;dsmith\@datarecall.net&gt;,	&lt;dsmith\@dasia.net&gt;
MATCH gentoo-announce\@gentoo.org
MATCH elia\@tpkm.ru, rescuebre\@tpkm.ru, kcruz\@rltvty.com, bugtracker\@rltvty.com
MATCH rescuebre\@tpkm.ru, bugs\@drnn.net, kcruz\@rltvty.com, bugtracker\@rltvty.com
MATCH &lt;Undisclosed Recipients&gt;
MATCH cfzvcvhr\@worldnet.att.net
MATCH &quot;Armlet Forum&quot; &lt;armlet-forum\@news.palmos.com&gt;
MATCH &lt;webmaster\@jgc.org&gt;
MATCH spamaddy\@domain

MATCH Re[69537]: Information for YOU
MATCH ADV: Turn Back the Hands of Time - Compl...
MATCH Luscious Black Nymphos!
MATCH test for various HTML parts
MATCH Enlarge your package Doctor ApprovedNHOB...
MATCH Fix for kde 3.1+3.0.x installs (x86) (bu..
MATCH VI ID: 24149  Status: Dev Confirmed Fix ..
MATCH VI ID: 24052  Status: Open  Sev: 2
MATCH Mooo
MATCH 5uj9s
MATCH (Archive Copy) RE: CW v9 and armlets..
MATCH [spam] Want to see a huge horse c*ck in ...
MATCH spamaddy,what ?
MATCH &lt;subject header missing&gt;
MATCH blank

MATCH <a href="/buckets?session=$sk&amp;showbucket=spam">
MATCH
<span style="color:blue">
spam
</span>
ENDMATCH
MATCH &lt;&nbsp;Arrived
MATCH
<a href="/history?session=$sk&amp;setsort=from">
From
</a>
ENDMATCH

MATCH reclassify_11
MATCH remove_11
MATCH rowid_11
MATCH /view\?view=11
MATCH reclassify_12
MATCH remove_12
MATCH rowid_12
MATCH /view\?view=12
MATCH reclassify_13
MATCH remove_13
MATCH rowid_13
MATCH /view\?view=13
MATCH reclassify_14
MATCH remove_14
MATCH rowid_14
MATCH /view\?view=14
MATCH reclassify_15
MATCH remove_15
MATCH rowid_15
MATCH /view\?view=15
MATCH reclassify_16
MATCH remove_16
MATCH rowid_16
MATCH /view\?view=16
MATCH reclassify_17
MATCH remove_17
MATCH rowid_17
MATCH /view\?view=17
MATCH reclassify_18
MATCH remove_18
MATCH rowid_18
MATCH /view\?view=18
MATCH reclassify_19
MATCH remove_19
MATCH rowid_19
MATCH /view\?view=19
MATCH reclassify_20
MATCH remove_20
MATCH rowid_20
MATCH /view\?view=20
MATCH reclassify_21
MATCH remove_21
MATCH rowid_21
MATCH /view\?view=21
MATCH reclassify_22
MATCH remove_22
MATCH rowid_22
MATCH /view\?view=22
MATCH reclassify_23
MATCH remove_23
MATCH rowid_23
MATCH /view\?view=23
MATCH reclassify_24
MATCH remove_24
MATCH rowid_24
MATCH /view\?view=24
MATCH reclassify_25
MATCH remove_25
MATCH rowid_25
MATCH /view\?view=25
MATCH reclassify_26
MATCH remove_26
MATCH rowid_26
MATCH /view\?view=26
MATCH reclassify_27
MATCH remove_27
MATCH rowid_27
MATCH /view\?view=27
MATCH reclassify_28
MATCH remove_28
MATCH rowid_28
MATCH /view\?view=28
MATCH reclassify_29
MATCH remove_29
MATCH rowid_29
MATCH /view\?view=29
MATCH reclassify_30
MATCH remove_30
MATCH rowid_30
MATCH /view\?view=30


# Check the page navigator

MATCH
Jump to page:
<b>1</b>
[<a href="/history?start_message=20&amp;session=$sk&amp;sort=-inserted">2</a>]
[<a href="/history?start_message=20&amp;session=$sk&amp;sort=-inserted">Next &gt;</a>]
ENDMATCH
GET /history?start_message=20&amp;session=$sk&amp;sort=-inserted
MATCH
Jump to page:
[<a href="/history?start_message=0&amp;session=$sk&amp;sort=-inserted">&lt; Previous</a>]
[<a href="/history?start_message=0&amp;session=$sk&amp;sort=-inserted">1</a>]
<b>2</b>
ENDMATCH
NOTMATCH &quot;Dr. Robert Ezenshtein&quot; &lt;phrekiesomeone\@
NOTMATCH asdfsomebody\@mbnet.fi
NOTMATCH &lt;elia\@tpkm.ru&gt;
NOTMATCH Enlarge your package Doctor ApprovedNHOB
NOTMATCH Douglas Arnold &lt;0noy8\@worldnet.att.net&gt;
GET /history

# Check refresh

NOTMATCH Testing Refresh
MATCH (<a class="history" href="/history?session=$sk">Refresh</a>)
NEWMSG 1
GET /history?session=$sk
MATCH John
MATCH Testing Refresh
MATCH personal

# Check magnet classified mails

NOTMATCH Magnetic Attraction for Ferrous Females
MATCH (<a class="history" href="/history?session=$sk">Refresh</a>)
NEWMSG 2
GET /history?session=$sk&amp;setfilter=
MATCH foo-magnet\@magnetmania.com
MATCH Magnetic Attraction for Ferrous Females
MATCH personal
MATCH <img title="foo" alt="foo" src="/skins/default/magnet.png">

GET /view?view=32&amp;start_message=0&amp;session=$sk
MATCH Single Message View
MATCH foo-magnet\@magnetmania.com
MATCH Magnetic Attraction for Ferrous Females
MATCH
<b>
Magnet used:
</b>
</font>
<font size="+1">
foo
</font>
ENDMATCH

MATCH <a class="messageLink" href="#message_header">Message Header</a>
NOTMATCH | <a class="messageLink" href="#message_body">Message Body</a>
NOTMATCH | <a class="messageLink" href="#quick_magnet">QuickMagnet</a>
NOTMATCH | <a class="messageLink" href="#scores">Scores</a>
MATCH <a name="message_header" />

# Check search

GET /history
SETSUBMIT search isnotpresent
MATCH No matching messages.
NOTMATCH Jump to page
CLICK reset_filter_search
NOTMATCH searched for from/subject
NOTMATCH No matching messages.
MATCH Douglas Arnold &lt;0noy8\@worldnet.att.net&gt;
MATCH Jump to page

SETSUBMIT search test.com
MATCH test\@test.com
NOTMATCH Enlarge your package Doctor ApprovedNHOB...
NOTMATCH Jump to page
CLICK reset_filter_search
NOTMATCH searched for from/subject
NOTMATCH No matching messages.
MATCH Douglas Arnold &lt;0noy8\@worldnet.att.net&gt;
MATCH Jump to page

SETSUBMIT search Doctor
NOTMATCH test\@test.com
MATCH Enlarge your package Doctor ApprovedNHOB...
NOTMATCH Jump to page
CLICK reset_filter_search
NOTMATCH No matching messages.
MATCH Douglas Arnold &lt;0noy8\@worldnet.att.net&gt;
MATCH Jump to page

SETSUBMIT search "
NOTMATCH """
MATCH "&quot;"
CLICK reset_filter_search

# Check search filter highlight

NOTMATCH historySearchFilterActive
SETCONFIG html_search_filter_highlight 1
SETSUBMIT search Doctor
MATCH historySearchFilterActive
SETCONFIG html_search_filter_highlight 0
SETSUBMIT search Doctor
NOTMATCH historySearchFilterActive
CLICK reset_filter_search
NOTMATCH historySearchFilterActive

# Check filter

SETINPUT filter personal
CLICK setfilter
MATCH <option value="personal" selected style="color: green">
NOTMATCH Douglas Arnold &lt;0noy8\@worldnet.att.net&gt;
MATCH Testing Refresh
CLICK reset_filter_search
SETINPUT filter spam
CLICK setfilter
MATCH Douglas Arnold &lt;0noy8\@worldnet.att.net&gt;
NOTMATCH Testing Refresh
MATCH
Jump to page:
<b>1</b>
[<a href="/history?start_message=20&amp;session=$sk&amp;filter=spam&amp;sort=-inserted">2</a>]
[<a href="/history?start_message=20&amp;session=$sk&amp;filter=spam&amp;sort=-inserted">Next &gt;</a>]
ENDMATCH

GET /history?start_message=20&amp;session=$sk&amp;filter=spam
NOTMATCH Testing Refresh
SETINPUT filter other
CLICK setfilter
MATCH No matching messages.
SETINPUT filter __filter__magnet
CLICK setfilter
MATCH Magnetic Attraction for Ferrous Females
NOTMATCH Testing Refresh
HIDDEN 0
SETINPUTN negate 2 on
CLICK setfilter
NOTMATCH Magnetic Attraction for Ferrous Females
MATCH Testing Refresh
SETINPUTN negate 2 off
CLICK setfilter
MATCH Magnetic Attraction for Ferrous Females
NOTMATCH Testing Refresh
CLICK setfilter
MATCH Magnetic Attraction for Ferrous Females
NOTMATCH Testing Refresh

# Check search filter highlight

NOTMATCH historySearchFilterActive
SETCONFIG html_search_filter_highlight 1
SETINPUT filter spam
CLICK setfilter
MATCH historySearchFilterActive
SETCONFIG html_search_filter_highlight 0
SETINPUT filter spam
CLICK setfilter
NOTMATCH historySearchFilterActive
CLICK reset_filter_search
NOTMATCH historySearchFilterActive

# Check that reclassification doesn't clear the negate
# flag

HIDDEN 0
SETINPUT filter __filter__magnet
SETINPUTN negate 2 on
CLICK setfilter
NOTMATCH Magnetic Attraction for Ferrous Females
MATCH Testing Refresh
CLICK change
NOTMATCH Magnetic Attraction for Ferrous Females
MATCH Testing Refresh
CLICK reset_filter_search

# Check sorting

MATCH
<a href="/history?session=$sk&amp;setsort=bucket">
Bucket
</a>
ENDMATCH

GET /history?session=$sk&amp;setsort=bucket
MATCH
<td>
<a href="/buckets?session=$sk&amp;showbucket=personal">
<span style="color:green">
personal
</span>
</a>
</td>
ENDMATCH
MATCH
<th class="historyLabel" scope="col" align="left">
<a href="/history?session=$sk&amp;setsort=-bucket">
<em class="historyLabelSort">
&gt;&nbsp;Bucket
</em>
</a>
</th>
ENDMATCH

GET /history?session=$sk&amp;setsort=-bucket
MATCH
<th class="historyLabel" scope="col" align="left">
<a href="/history?session=$sk&amp;setsort=bucket">
<em class="historyLabelSort">
&lt;&nbsp;Bucket
</em>
</a>
</th>
ENDMATCH

GET /history?session=$sk&amp;setsort=

# Check reclassification

GET /history
MATCH Testing Refresh
SETINPUT reclassify_31 spam
CLICK change
MATCH Changed to <font color="blue">spam</font>
MATCH Reclassified

# Check reclassified filter

GET /history
SETINPUT filter __filter__reclassified
CLICK setfilter
MATCH <option value="__filter__reclassified" selected>
MATCH Testing Refresh
MATCH <span class="reclassifyText">Reclassified</span>
NOTMATCH Magnetic Attraction

SETINPUTN negate 2 on
CLICK setfilter
MATCH <option value="__filter__reclassified" selected>
MATCH Magnetic Attraction
NOTMATCH <span class="reclassifyText">Reclassified</span>
NOTMATCH Testing Refresh

CLICK reset_filter_search
MATCH <option value="__filter__reclassified" >
MATCH Testing Refresh
MATCH Magnetic Attraction

# Check undo

CLICK undo_31
MATCH
<td>
<a class="messageLink" title="Testing Refresh" href="/view?view=31&amp;start_message=0&amp;session=$sk&amp;sort=-inserted">
Testing Refresh
</a>
</td>
<td>
<a href="/buckets?session=$sk&amp;showbucket=personal">
<span style="color:green">
personal
</span>
</a>
</td>
ENDMATCH

# Check click through from bucket name

MATCH
<td>
<a href="/buckets?session=$sk&amp;showbucket=spam">
<span style="color:blue">
spam
</span>
</a>
</td>
ENDMATCH

# bucket page

GET /buckets?session=$sk&showbucket=spam
MATCH Detail for <font color="blue">spam</font>

GET /history

# Single message view for accuracy

MATCH
<td>
<a class="messageLink" title="Testing Refresh" href="/view?view=31&amp;start_message=0&amp;session=$sk&amp;sort=-inserted">
Testing Refresh
</a>
</td>
ENDMATCH

GET /view?view=31&amp;start_message=0&amp;session=$sk
MATCH Single Message View
MATCH Testing Refresh
MATCH John
MATCH
<td>
<font size="+1">
<b>
Bucket:
</b>
</font>
</td>
<td>
<font size="+1">
<span style="color:green">
personal
</span>
</font>
</td>
ENDMATCH

MATCH
<a class="messageLink" href="#message_header">Message Header</a>
| <a class="messageLink" href="#message_body">Message Body</a>
| <a class="messageLink" href="#quick_magnets">QuickMagnets</a>
| <a class="messageLink" href="#scores">Scores</a>
ENDMATCH
MATCH <a name="message_header" />
MATCH <a name="message_body" />
MATCH
<a name="quick_magnets">
QuickMagnets
</a>
ENDMATCH
MATCH
<a name="scores">
Scores
</a>
ENDMATCH

MATCH Scores
MATCH 0.769209
MATCH 0.230763
MATCH 2.829186e-05
MATCH <font color="red">here</font>
NOTMATCH 0.3289
NOTMATCH 0.6697
MATCH <font color="black">John</font>
MATCH <font color="red">here</font>
MATCH Body would

GET /view?view=31&amp;start_message=0&amp;session=$sk&amp;format=prob
MATCH showing word probabilities
MATCH 0.7692
MATCH 0.2308

GET /view?view=31&amp;start_message=0&amp;session=$sk&amp;format=freq
MATCH showing word frequencies
MATCH 0.00165
MATCH 0.00336

GET /view?view=31&amp;start_message=0&amp;session=$sk&amp;format=score
MATCH showing word scores
MATCH 2.3639
MATCH 2.6727

GET   /view?view=31&amp;start_message=0&amp;session=$sk&amp;text=1
MATCH From: John
MATCH Subject: Testing Refresh
MATCH Body would go here

# Jump to message

GET /jump_to_message?view=31
MATCH Single Message View
MATCH Testing Refresh
MATCH John
MATCH
<td>
<font size="+1">
<span style="color:green">
personal
</span>
</font>
</td>
ENDMATCH
MATCH Scores
MATCH 0.769209
MATCH 0.230763
MATCH 2.829186e-05
MATCH <font color="red">here</font>
NOTMATCH 0.3289
NOTMATCH 0.6697
MATCH <font color="black">John</font>
MATCH <font color="red">here</font>
# MATCH Body would

GET /jump_to_message?view=40
NOTMATCH Single Message View
MATCH Recent Messages

# jump_to_message and a password

#GET /security
#INPUTIS password
#CONFIGIS html_password
#SETSUBMIT password secret
#GET /jump_to_message?view=popfile10000=1.msg
#MATCH Enter password:
#SETSUBMIT password secret
#MATCH Single Message View
#MATCH Testing Refresh
#SETCONFIG html_password
#GET /security
#SETSUBMIT password
#MATCH Updated password to

# Quick Magnets

GET /jump_to_message?view=31
MATCH Single Message View
MATCH
<option value="Testing">
Testing
</option>
ENDMATCH
MATCH
<option value="Refresh">
Refresh
</option>
ENDMATCH
MATCH
<option value="John">
John
</option>
ENDMATCH
SETINPUT text1 John
SETINPUT bucket1 other
CLICK create
MATCH Current Magnets
MATCH <input type="text" name="text1" value="John" size="50" />
SETINPUT remove1 on
CLICK delete

# Reclassify from single message view

GET /view?view=31&amp;start_message=0&amp;session=$sk
MATCH Single Message View
MATCH Testing Refresh
SETINPUT reclassify_31 spam
CLICK change
MATCH Changed to <font color="blue">spam</font>

# Undo on single message view

GET /view?view=31&amp;start_message=0&amp;session=$sk
MATCH Single Message View
CLICK undo_31
MATCH
<td>
<a class="messageLink" title="Testing Refresh" href="/view?view=31&amp;start_message=0&amp;session=$sk">
Testing Refresh
</a>
</td>
<td>
<a href="/buckets?session=$sk&amp;showbucket=personal">
<span style="color:green">
personal
</span>
</a>
</td>
ENDMATCH

# Check delete one message

GET /history
MATCH Testing Refresh
SETINPUT remove_31 on
CLICK clearchecked
MATCH Recent Messages
NOTMATCH Testing Refresh

# Check delete some messages

MATCH gentoo-announce
MATCH Armlet Forum
SETINPUT remove_20 on
SETINPUT remove_13 on
CLICK clearchecked
NOTMATCH gentoo-announce
NOTMATCH Armlet Forum

# Check delete page of messages

GET /history
CLICK clearpage
NOTMATCH Jump to message
MATCH Recent Messages (9)
MATCH Hello,Let us enjoy life

# Check delete all messages

CLICK clearall
MATCH No messages.

# Magnets Page

GET /magnets

# Check that predefined magnets are present

INPUTIS text1 foo
INPUTIS bucket1 personal
INPUTIS type1 from
INPUTIS text2 oldstyle
INPUTIS bucket2 personal
INPUTIS type2 from
INPUTIS text3 bar
INPUTIS bucket3 personal
INPUTIS type3 subject
INPUTIS text4 baz\@baz.com
INPUTIS bucket4 personal
INPUTIS type4 to

# Check magnet creation

SETINPUT  text0 newmagnet
SETINPUT  type0 subject
SETSUBMIT bucket0 spam
INPUTIS   text5 newmagnet
INPUTIS   type5 subject
INPUTIS   bucket5 spam
MAGNETIS  spam subject newmagnet

SETINPUT text0 foo
SETINPUT type0 from
SETSUBMIT bucket0 personal
MATCH Magnet &#39;from: foo&#39; already exists in bucket &#39;personal&#39;
NOTMATCH &lt;br

SETINPUT text0 foo bar
SETINPUT type0 from
SETSUBMIT bucket0 personal
MATCH New magnet &#39;from: foo bar&#39; clashes with magnet &#39;from: foo&#39; in bucket &#39;personal&#39; and could cause ambiguous results.  New magnet was not added.
NOTMATCH &lt;br

# Check magnet change value

SETSUBMIT text5 newmagnetvalue
INPUTIS   text5 newmagnetvalue
INPUTIS   type5 subject
INPUTIS   bucket5 spam
MAGNETIS  spam subject newmagnetvalue
INPUTIS text1 foo
INPUTIS bucket1 personal
INPUTIS type1 from
INPUTIS text2 oldstyle
INPUTIS bucket2 personal
INPUTIS type2 from
INPUTIS text3 bar
INPUTIS bucket3 personal
INPUTIS type3 subject
INPUTIS text4 baz\@baz.com
INPUTIS bucket4 personal
INPUTIS type4 to

# Check magnet change type

SETSUBMIT type5 to
INPUTIS   type5 to
INPUTIS   text5 newmagnetvalue
INPUTIS   bucket5 spam
MAGNETIS  spam to newmagnetvalue
INPUTIS text1 foo
INPUTIS bucket1 personal
INPUTIS type1 from
INPUTIS text2 oldstyle
INPUTIS bucket2 personal
INPUTIS type2 from
INPUTIS text3 bar
INPUTIS bucket3 personal
INPUTIS type3 subject
INPUTIS text4 baz\@baz.com
INPUTIS bucket4 personal
INPUTIS type4 to

# Check magnet change bucket

SETSUBMIT bucket5 personal
INPUTIS   bucket5 personal
INPUTIS   text5 newmagnetvalue
INPUTIS   type5 to
MAGNETIS  personal to newmagnetvalue
INPUTIS text1 foo
INPUTIS bucket1 personal
INPUTIS type1 from
INPUTIS text2 oldstyle
INPUTIS bucket2 personal
INPUTIS type2 from
INPUTIS text3 bar
INPUTIS bucket3 personal
INPUTIS type3 subject
INPUTIS text4 baz\@baz.com
INPUTIS bucket4 personal
INPUTIS type4 to

# Check the magnet navigator

GET /configuration
SETSUBMIT page_size 3

GET /magnets
MATCH
Jump to magnet page:
<b>1</b>
[<a href="/magnets?start_magnet=3&amp;session=$sk">2</a>]
[<a href="/magnets?start_magnet=3&amp;session=$sk">Next</a>]
ENDMATCH

GET /magnets?start_magnet=3&amp;session=$sk
MATCH
Jump to magnet page:
[<a href="/magnets?start_magnet=0&amp;session=$sk">Previous</a>]
[<a href="/magnets?start_magnet=0&amp;session=$sk">1</a>]
<b>2</b>
ENDMATCH

GET /configuration
SETSUBMIT page_size 20

# Check magnet deletion

GET /magnets
SETINPUT remove5 on
CLICK delete
NOTMATCH newmagnetvalue
NOTMATCH type5

SETINPUT remove1 on
SETINPUT remove3 on
CLICK delete
NOTMATCH "foo"
NOTMATCH bar
INPUTIS text1 oldstyle
INPUTIS bucket1 personal
INPUTIS type1 from
INPUTIS text2 baz\@baz.com
INPUTIS bucket2 personal
INPUTIS type2 to
NOTMATCH type3

# Configuration Page

GET /configuration

# Check skin change

MATCH <link rel="stylesheet" type="text/css" href="skins/simplyblue/style.css" title="POPFile">
CONFIGIS html_skin simplyblue
SETSUBMIT skin oceanblue
MATCH <link rel="stylesheet" type="text/css" href="skins/oceanblue/style.css" title="POPFile">
CONFIGIS html_skin oceanblue
SETSUBMIT skin default
CONFIGIS html_skin default

# Check language change

MATCH <html lang="en">
CONFIGIS html_language English
SETSUBMIT language Francais
MATCH <html lang="fr">
CONFIGIS html_language Francais
SETSUBMIT language English
MATCH <html lang="en">
CONFIGIS html_language English

# Check logger change

INPUTIS   debug 2
CONFIGIS  GLOBAL_debug 1
SETSUBMIT debug 3
INPUTIS   debug 3
CONFIGIS  GLOBAL_debug 2
SETSUBMIT debug 4
INPUTIS   debug 4
CONFIGIS  GLOBAL_debug 3
SETSUBMIT debug 1
INPUTIS   debug 1
CONFIGIS  GLOBAL_debug 0

# Check history lines change

INPUTIS   page_size 20
CONFIGIS  html_page_size 20
SETSUBMIT page_size 30
INPUTIS   page_size 30
CONFIGIS  html_page_size 30
MATCH Updated number of messages per page to 30
SETSUBMIT page_size 0
MATCH The page size must be a number between 1 and 1000
INPUTIS   page_size 30

# Check history days change

INPUTIS   history_days 2
CONFIGIS  history_history_days 2
SETSUBMIT history_days 3
INPUTIS   history_days 3
CONFIGIS  history_history_days 3
MATCH Updated number of days of history to 3
SETSUBMIT history_days 0
MATCH The number of days in the history must be a number between 1 and 366
INPUTIS   history_days 3

# Check change timeout

INPUTIS   timeout 60
CONFIGIS  GLOBAL_timeout 60
SETSUBMIT timeout 61
INPUTIS   timeout 61
CONFIGIS  GLOBAL_timeout 61
MATCH Updated connection timeout to 61
SETSUBMIT timeout 0
MATCH The TCP timeout must be a number between 10 and 1800
INPUTIS   timeout 61

# Check change POP3 port

INPUTIS   pop3_port 9110
CONFIGIS  pop3_port 9110
SETSUBMIT pop3_port 111
INPUTIS   pop3_port 111
CONFIGIS  pop3_port 111
MATCH Updated POP3 port to 111; this change will not take affect until you restart POPFile
SETSUBMIT pop3_port 0
MATCH The POP3 listen port must be a number between 1 and 65535
INPUTIS   pop3_port 111
SETSUBMIT pop3_port $port
MATCH The POP3 listen port cannot be the same value as the user interface port
INPUTIS   pop3_port 111

# Check change separator

INPUTIS   pop3_separator :
CONFIGIS  pop3_separator :
SETSUBMIT pop3_separator ;
INPUTIS   pop3_separator ;
CONFIGIS  pop3_separator ;
MATCH Updated POP3 separator to ;
SETSUBMIT pop3_separator gg
MATCH The separator character must be a single character
INPUTIS   pop3_separator ;

# Check fork for POP3

HIDDEN 1
INPUTIS   pop3_force_fork 1
CONFIGIS  pop3_force_fork 0
SETSUBMIT pop3_force_fork 0
INPUTIS   pop3_force_fork 1
CONFIGIS  pop3_force_fork 0
SETSUBMIT pop3_force_fork 1
INPUTIS   pop3_force_fork 0
HIDDEN 0

# Check UI port

INPUTIS   ui_port $port
CONFIGIS  html_port $port
SETSUBMIT ui_port 8082
INPUTIS   ui_port 8082
CONFIGIS  html_port 8082
MATCH Updated user interface web port to 8082; this change will not take affect until you restart POPFile
SETSUBMIT ui_port 0
MATCH The user interface port must be a number between 1 and 65535
INPUTIS   ui_port 8082
SETSUBMIT ui_port 111
MATCH The user interface port cannot be the same value as the POP3 listen port
INPUTIS   ui_port 8082

# Security Page

GET /security

# Check POP3 stealth

HIDDEN 1
INPUTIS pop3_local 1
CONFIGIS pop3_local 1
SETSUBMIT pop3_local 1
INPUTIS pop3_local 2
CONFIGIS pop3_local 0
SETSUBMIT pop3_local 2
INPUTIS pop3_local 1
CONFIGIS pop3_local 1
HIDDEN 0

# Check UI stealth

HIDDEN 1
INPUTIS localui 1
CONFIGIS html_local 1
SETSUBMIT localui 1
INPUTIS localui 2
CONFIGIS html_local 0
SETSUBMIT localui 2
INPUTIS localui 1
CONFIGIS html_local 1
HIDDEN 0

# Check POP3 AUTH options

INPUTIS   server
CONFIGIS  pop3_secure_server
SETSUBMIT server secure.com
INPUTIS   server secure.com
CONFIGIS  pop3_secure_server secure.com
MATCH Updated remote POP3 server to secure.com

INPUTIS   sport 110
CONFIGIS  pop3_secure_port 110
SETSUBMIT sport 111
INPUTIS   sport 111
CONFIGIS  pop3_secure_port 111
MATCH Updated remote POP3 server port to 111
SETSUBMIT sport 0
INPUTIS   sport 111
CONFIGIS  pop3_secure_port 111
MATCH The port must be a number between 1 and 65535

# Check autoupdate

HIDDEN 1
INPUTIS update_check 2
CONFIGIS GLOBAL_update_check 0
SETSUBMIT update_check 1
INPUTIS update_check 2
CONFIGIS GLOBAL_update_check 0
SETSUBMIT update_check 2
INPUTIS update_check 1
CONFIGIS GLOBAL_update_check 1
HIDDEN 0

# Check statistics sending

HIDDEN 1
INPUTIS send_stats 2
CONFIGIS html_send_stats 0
SETSUBMIT send_stats 1
INPUTIS send_stats 2
CONFIGIS html_send_stats 0
SETSUBMIT send_stats 2
INPUTIS send_stats 1
CONFIGIS html_send_stats 1
HIDDEN 0

# Check password

INPUTIS password
CONFIGIS html_password b61124a488acc5f4406e74272629ee86
SETSUBMIT password secret
CONFIGIS html_password d5a642c75542722fd0e20993ee36765d
MATCH Updated password
SETSUBMIT password
INPUTIS password
CONFIGIS html_password b61124a488acc5f4406e74272629ee86
MATCH Updated password

# Advanced Page

GET /advanced

# Check presence of ignore words

MATCH address
MATCH localhost
MATCH smtp

# Check add ignore word

INPUTIS newword
SETSUBMIT newword four11@.-_
MATCH four11@.-_
SETSUBMIT newword ba"d
MATCH Ignored words can only contain alphanumeric, ., _, -, or @ characters

# Check remove ignore word

INPUTIS word
SETSUBMIT word four11@.-_
NOTMATCH four11@.-_
SETSUBMIT word ba"d
MATCH Ignored words can only contain alphanumeric, ., _, -, or @ characters

# TODO Write better tests for stop words in Japanese
# and Korean

GET /configuration
SETSUBMIT language Nihongo
GET /advanced
MATCH address
MATCH localhost
MATCH smtp

GET /configuration
SETSUBMIT language Korean
GET /advanced
MATCH address
MATCH localhost
MATCH smtp

GET /configuration
SETSUBMIT language English

# Check change arbitrary parameter

GET /advanced
SETSUBMIT parameter_bayes_hostname testhostname
CONFIGIS bayes_hostname testhostname
INPUTIS parameter_bayes_hostname testhostname

# Buckets Page

GET /buckets

# Basic bucket test to verify that the buckets in the test corpus
# are present on the bucket page with the right numbers
#
#     Checks bucket names are present and the word and unique word
#     counts

MATCH spam
MATCH personal
MATCH other

MATCH <a href="/buckets?session=$sk&amp;showbucket=spam">
MATCH <a href="/buckets?session=$sk&amp;showbucket=personal">
MATCH <a href="/buckets?session=$sk&amp;showbucket=other">

MATCH
<td align="right">
656
</td>
ENDMATCH
MATCH
<td align="right">
3
</td>
ENDMATCH
MATCH
<td align="right">
3,353
</td>
ENDMATCH

# Check statistics displayed correctly

MATCH 1,785 (12.74%)
MATCH 103 (0.73%)
MATCH 12,114 (86.51%)

MATCH <td bgcolor="green" title="personal (75.61)" width="75.61%">
MATCH <td bgcolor="blue" title="spam (24.39)" width="24.39%">

# Check Reset Statistics

MATCH
<td align="right">
656
</td>
ENDMATCH
MATCH
<td align="right">
3
</td>
ENDMATCH
MATCH
<td align="right">
99.39%
</td>
ENDMATCH
CLICK reset_stats
MATCH
<td align="right">
Not enough data
</td>
ENDMATCH
MATCH
<td align="right">
0 (  0.00%)
</td>
ENDMATCH

# Check bucket creation

NOTMATCH newbucket0-_
SETSUBMIT cname newbucket0-_
MATCH newbucket0-_
MATCH Created bucket named newbucket0-_
MATCH
<td align="left">
<a href="/buckets?session=$sk&amp;showbucket=newbucket0-_">
<span style="color:black">
newbucket0-_
</span>
</a>
</td>
ENDMATCH

SETSUBMIT cname bu%cket
MATCH Bucket names can only contain the letters a to z in lower case
SETSUBMIT cname BUCKET
MATCH Bucket names can only contain the letters a to z in lower case

SETSUBMIT cname spam
MATCH Bucket named spam already exists

MATCH spam
MATCH personal
MATCH other

# Check set bucket color

GET /buckets?newbucket0-__color=blue&bucket=newbucket0-_&bucket_settings=1&session=$sk
MATCH
<td align="left">
<a href="/buckets?session=$sk&amp;showbucket=newbucket0-_">
<span style="color:blue">
newbucket0-_
</span>
</a>
</td>
ENDMATCH

# Check bucket rename

SETINPUT oname newbucket0-_
SETSUBMIT newname sens%ible
MATCH Bucket names can only contain the letters a to z in lower case
SETINPUT oname newbucket0-_
SETSUBMIT newname sensible
MATCH Renamed bucket newbucket0-_ to sensible
MATCH
<td align="left">
<a href="/buckets?session=$sk&amp;showbucket=sensible">
<span style="color:blue">
sensible
</span>
</a>
</td>
ENDMATCH

MATCH spam
MATCH personal
MATCH other

# Check bucket delete

SETSUBMIT name sensible
MATCH Deleted bucket sensible

GET /buckets

NOTMATCH sensible
MATCH spam
MATCH personal
MATCH other

# Check word lookup

SETSUBMIT word xxxxxx
MATCH <b>xxxxxx</b> does not appear in any of the buckets
SETSUBMIT word used
MATCH <b>used</b> is most likely to appear in <font color="red">other</font>
MATCH 0.0005602241
MATCH 0.6873803233
MATCH 1.8945518529
MATCH Frequency
SETSUBMIT word address
MATCH <b>address</b> is in Ignored Words. POPFile ignores this word

# Check operation of Subject Modification

SETSUBMIT name personal
MATCH Deleted bucket personal
SETSUBMIT name other
MATCH Deleted bucket other

#HIDDEN 1
INPUTIS spam_subject
PARAMETERIS spam subject 0
SETSUBMIT spam_subject off
INPUTIS spam_subject
PARAMETERIS spam subject 0
SETSUBMIT spam_subject on
INPUTIS spam_subject on
PARAMETERIS spam subject 1
#HIDDEN 0

# Check operation of Quarantine

#HIDDEN 1
INPUTIS spam_quarantine
PARAMETERIS spam quarantine 0
SETSUBMIT spam_quarantine on
INPUTIS spam_quarantine on
PARAMETERIS spam quarantine 1
SETSUBMIT spam_quarantine off
INPUTIS spam_quarantine
PARAMETERIS spam quarantine 0
#HIDDEN 0

# Check operation of color change

GET /buckets?spam_color=purple&bucket=spam&bucket_settings=1&session=$sk
MATCH <option value="purple"  selected style="color: purple">

# Check individual bucket page for accuracy

MATCH /buckets?session=$sk&amp;showbucket=spam
GET /buckets?session=$sk&amp;showbucket=spam
MATCH Detail for <font color="purple">spam</font>
MATCH 12,114
MATCH (3,353 distinct)
MATCH
<td>
100.00%
</td>
ENDMATCH
MATCH <a class="bucketLetter" href="/buckets?session=$sk&amp;showbucket=spam&amp;showletter=m">

GET /buckets?session=$sk&amp;showbucket=spam&amp;showletter=m
MATCH <a class="wordListLink" href="/buckets?session=$sk&amp;lookup=Lookup&amp;word=missouri#Lookup">

# Check clearing of individual bucket

CLICK clearbucket
MATCH
<th scope="row" class="bucketsLabel">
Total word count
</th>
<td>
&nbsp;
</td>
<td>
0
</td>
ENDMATCH

# Check bad session key

GET /history?session=123456
MATCH POPFile Session Expired

# Get ICO, GIF, CSS, PNG, LOG and HTML file

CODE
open TEMP, ">../temp.ico";
print TEMP "10 GOTO 10\n";
close TEMP;
ENDCODE

GET /temp.ico
MATCH 10 GOTO 10

CODE
rename '../temp.ico', '../temp.gif';
ENDCODE

GET /temp.gif
MATCH 10 GOTO 10

CODE
rename '../temp.gif', '../temp.png';
ENDCODE

GET /temp.png
MATCH 10 GOTO 10

CODE
unlink '../temp.png';
ENDCODE

GET /popfile_current_log.log
MATCH Attempting to connect to dbi:SQLite:dbname=../tests/popfile.db

CODE
mkdir '../manual';
open TEMP, ">../manual/temp.html";
print TEMP "10 GOTO 10\n";
close TEMP;
ENDCODE

GET /manual/temp.html
MATCH 10 GOTO 10

CODE
rmtree( '../manual' );
ENDCODE

GET /skins/default/style.css
MATCH .menuSelected

# Get a page that does not exist

GET /foo
MATCH POPFile Web Server Error 404

# Check update checking

SETCONFIG GLOBAL_update_check 1
SETCONFIG GLOBAL_send_stats 1
SETCONFIG GLOBAL_last_update_check 0
SETCONFIG GLOBAL_ecount 1
GET /
MATCH popfile_update.pl
MATCH popfile_stats.pl

# Check the operation of passwords

GET /security
INPUTIS password
CONFIGIS html_password b61124a488acc5f4406e74272629ee86
SETSUBMIT password secret
GET /advanced?session=123456
MATCH Enter password:
SETSUBMIT password wrong
MATCH Enter password:
MATCH Incorrect password
GET /?session=123456
MATCH Enter password:
SETSUBMIT password secret
MATCH Recent Messages
GET /advanced?session=123456&dummy=foo&dummy=bar
MATCH Enter password:
SETSUBMIT password secret
MATCH All POPFile Parameters
GET /password
MATCH Enter password:
SETSUBMIT password secret
MATCH Recent Messages
GET /security

# Check shutdown operation

GET /shutdown
MATCH Enter password:
SETSUBMIT password secret
MATCH POPFile has shut down
